services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  OliverKroener\OkPriveConsent\:
    resource: '../Classes/*'

  # Public: required for TypoScript USER function calls
  OliverKroener\OkPriveConsent\Service\DatabaseService:
    public: true
