services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  OliverKroener\OkPriveCookieConsent\:
    resource: '../Classes/*'

  # Public: required for TypoScript USER function calls
  OliverKroener\OkPriveCookieConsent\Service\DatabaseService:
    public: true
    arguments:
      $siteRootService: '@OliverKroener\Helpers\Service\SiteRootService'
